# $Id: Makefile,v 1.1 2006/12/04 16:28:29 mascarenhas Exp $

LUA_DIR= /home/yue/program/kepler-1.1/lua-5.1.2/src

install:
	mkdir -p $(LUA_DIR)/copas
	cp src/copas/copas.lua $(LUA_DIR)/copas
	ln -s $(LUA_DIR)/copas/copas.lua $(LUA_DIR)/copas.lua

clean:
